<br>
<div class="row">
   <img src="<?php echo $this->basePath('img/parent_page_1.png') ?>" alt="educators_home" style="width:100%" usemap="#parentmap"/>
   <map name="parentmap">
   	<area shape="rect" coords="450,550,750,600" href="<?php echo $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'index', 'id' => 'parent')) ?>" alt="parent register">
   </map>
</div>
<br>
