<br>
<div class="row">
   <img src="<?php echo $this->basePath('img/educators_page_1.png') ?>" alt="educators_home" style="width:100%" usemap="#educatormap"/>
   <map name="educatormap">
   	<area shape="rect" coords="450,550,750,600" href="<?php echo $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'index', 'id' => 'educator')) ?>" alt="educator register">
   </map>
</div>
<br>


<?php
/*$form = $this->form;
$form->setAttribute('action', $this->url('edufinder/default', array('controller' => 'educator', 'action' => 'search')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('postcode'));
echo $this->formSelect($form->get('curricular_name'));
echo $this->formSelect($form->get('year_or_grade_curricular')).'<br>';
echo $this->formSubmit($form->get('submit')).'<br>';
echo $this->form()->closeTag().'<br>';
*/
?>