<h1>Registration</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'index')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('first_name')).'<br>';
echo $this->formRow($form->get('last_name')).'<br>';
echo $this->formRow($form->get('email')).'<br>';
echo $this->formRow($form->get('password')).'<br>';
echo $this->formRow($form->get('password_confirm')).'<br>';
echo $this->formRow($form->get('captcha')).'<br>';
echo $this->formSubmit($form->get('submit')).'<br>';
echo $this->form()->closeTag().'<br>';
?>
<p>
	<a href="<?php echo $this->url('edufinder/default', array('controller' => 'index', 'action' => 'login'));?>"><?php echo $this->translate('Login'); ?></a> |
	<a href="<?php echo $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>