<br><br><br><br>
<div class="row">
	<div id="wowslider-container1">
      <div class="ws_images">
         <a href="<?php echo $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'index','id' => 'parent')) ?>"><img src="<?php echo $this->basePath('img/homepage_parents_withbg_f.png') ?>" alt="parents" style="width:100%"/></a>
      </div>
   </div>
</div>
<div class="row"></div>
<div class="row">
	<div id="wowslider-container1">
      <div class="ws_images">
         <a href="<?php echo $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'index', 'id' => 'educator')) ?>"><img src="<?php echo $this->basePath('img/homepage_educators_withbg_f.png') ?>" alt="educators" style="width:100%"/></a>
      </div>
   </div>
</div>