<br><br><br><br>
<div class="row" id="hat">
   <img src="<?php echo $this->basePath('img/bar_find_an_educator.png') ?>" alt="educator search" style="width:100%"/>
</div>
<br>
      <table class="table profile table-hover table-striped">
		<?php
			foreach ($rowset as $row) {
		?>
            <tr class="description">
            	<td style="width:15%">
               	 <div>
                    <?php if($row['picture']==null){
							 $pic_url = 'http://ec2-52-25-173-169.us-west-2.compute.amazonaws.com/img/uploads/uploadphoto_default.png';
							 }else{
								 $pic_url=$row['picture'];
						  }?>
               	    <img src="<?php echo $pic_url; ?>" alt="avatar" width="100%"/>
                   </div>                
               </td>
               <td>
              		 <?php echo $row['first_name'] ; ?>
                   <?php echo $row['last_name'] ; ?>
            	</td>
               <td>
              		 <?php echo $row['profile_description']; ?>
            	</td>
               <td>
              		 <?php echo '$ '.$row['hourly_rate_curricular'].'/h'; ?>
            	</td>
            </tr>
       <?php
			}
		?>
          </table> 
<div class="jumbotron">
   <h4> Educators in this area Postcode: <?php echo $this->postcode; if ($this->postcode == null){echo "no postcode specified!";}?></h4>
	<?php echo $this->map_html; ?>
</div>            
   </div>
