<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/edufinder.css')) 
                        ->prependStylesheet($this->basePath('css/engine1/style.css')) 
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
								?>

        <!-- Scripts -->
        <?php echo $this->headScript()
		  		->prependFile($this->basePath('js/edufinder.js'))
        		->prependFile($this->basePath('js/engine1/jquery.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9'))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php //echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li ><a href="<?php echo $this->url('edufinder/default', array('controller' => 'parent', 'action' => 'index')) ?>"><?php echo $this->translate('Parent') ?></a></li>
                        <li ><a href="<?php echo $this->url('edufinder/default', array('controller' => 'educator', 'action' => 'index')) ?>"><?php echo $this->translate('Educator') ?></a></li>
                        <li ><a href="<?php echo $this->url('edufinder') ?>"><?php echo $this->translate('Success Stories') ?></a></li>
                        <li ><a href="<?php echo $this->url('edufinder') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
                    </ul>
                      <ul class="nav navbar-nav navbar-right hdright">
                        <li ><a class="navbar-brand" href="<?php echo $this->url('edufinder/default', array('controller' => 'registration', 'action' => 'index')) ?>"><img src="<?php echo $this->basePath('img/signup.png') ?>" alt="sign up"/></a></li>
                        <li ><a class="navbar-brand" href="<?php echo $this->url('edufinder/default', array('controller' => 'index', 'action' => 'login')) ?>"><img src="<?php echo $this->basePath('img/login.png') ?>" alt="login"/></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
            <nav class="navbar " role="navigation">
               <div class="container">
                  <div class="collapse navbar-collapse">
                          <ul class="nav navbar-nav ftleft">
                              <li ><a href="<?php echo $this->url('edufinder') ?>"><?php echo $this->translate('Term of Use') ?></a></li>
                              <li ><a href="<?php echo $this->url('edufinder') ?>"><?php echo $this->translate('Privacy Policy') ?></a></li>
                              <li ><a href="<?php echo $this->url('edufinder') ?>"><?php echo $this->translate('Disclaimer') ?></a></li>
                              <li ><a href="<?php echo $this->url('edufinder') ?>"><?php echo $this->translate('Sitemap') ?></a></li>
                          </ul>
                          
                          <ul class="nav navbar-nav navbar-right ftright">
                              <li ><a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/twitter.png') ?>" alt="Zend Framework 2"/></a></li>
                              <li ><a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/facebook.png') ?>" alt="Zend Framework 2"/></a></li>
                              <li ><a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/google_plus.png') ?>" alt="Zend Framework 2"/></a></li>
                              <li ><a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Copyright 2015 EduFinder') ?></a></li>
                    			</ul>
                   </div> 
                </div>
             </nav>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
