
<div id="wowslider-container1">
    <div class="ws_images"><ul>
            <li><img src="img/data1/images/nbawallpaper.jpg" alt="nba-wallpaper" title="nba-wallpaper" id="wows1_0"/></li>
            <li><a href="http://wowslider.com"><img src="img/data1/images/nbabigcolor_framegrab_021.jpg" alt="jquery carousel" title="NBA-BIG-Color_frameGrab_02-1" id="wows1_1"/></a></li>
            <li><img src="img/data1/images/nbaplayoffs.jpg" alt="nba-playoffs" title="nba-playoffs" id="wows1_2"/></li>
        </ul></div>
        <div class="ws_bullets"><div>
            <a href="#" title="nba-wallpaper"><span><img src="img/data1/tooltips/nbawallpaper.jpg" alt="nba-wallpaper"/>1</span></a>
            <a href="#" title="NBA-BIG-Color_frameGrab_02-1"><span><img src="img/data1/tooltips/nbabigcolor_framegrab_021.jpg" alt="NBA-BIG-Color_frameGrab_02-1"/>2</span></a>
            <a href="#" title="nba-playoffs"><span><img src="img/data1/tooltips/nbaplayoffs.jpg" alt="nba-playoffs"/>3</span></a>
        </div></div><div class="ws_script" style="position:absolute;left:-99%"><a href="http://wowslider.com/vi">html5 slider</a> by WOWSlider.com v8.2</div>
    <div class="ws_shadow"></div>
</div>  
    <script type="text/javascript" src="js/engine1/wowslider.js"></script>
    <script type="text/javascript" src="js/engine1/script.js"></script>
    <!-- End WOWSlider.com BODY section -->

<div class="row">
    <hr>

</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><img src="<?php echo $this->basePath('img/2013-10-01-2k.jpg') ?>" alt="K-12 Curricular"/></p>
                <p><a class="btn btn-default" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('K-12 Curricular') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><img src="<?php echo $this->basePath('img/2013-10-01-2k.jpg') ?>" alt="Extracurriculaies"/></p>
                <p><a class="btn btn-default" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Extracurriculaies') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><img src="<?php echo $this->basePath('img/2013-10-01-2k.jpg') ?>" alt="Educators"/></p>
                <p><a class="btn btn-default" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Educators') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><img src="<?php echo $this->basePath('img/2013-10-01-2k.jpg') ?>" alt="Educational Resources"/></p>
                <p><a class="btn btn-default" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Educational Resources') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>

<div class="jumbotron">
     <h3><img src="<?php echo $this->basePath('img/k.png') ?>" alt="Educational Resources"/>K-12 Curricular <span class="label label-default">New</span></h3>
     <p>Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum </p>
</div>
